### ISSUE TITLE
Question about the necessity of a DSDT patch

### ISSUE THREAD

**Issue by sylv-io** [jakeday/surface-cameras#2]
Hello there,

I'm currently trying to get the rear camera working on a Lenovo ThinkPad X12 Detachable Gen1.
During my research i came across your repo, which requires to patch some acpi status methods and a field.

However, i did not understand why it is necessary :sweat_smile:. Dow did you come up with this solution?

thanks!

**Comment by jakeday** [comment]
@sylv-io Several devices do not ship with a complete or properly setup DSDT. At the time, patching the DSDT and loading in the custom version was the easiest solution to addressing hardware support. In more recent version of the kernel, support has been added to add these additional mappings so the DSDT patch is no longer required.

**Comment by sylv-io** [comment]
understood :+1: thanks
